language: node_js
os: linux
node_js:
  - node
before_install:
  - npm config set spin false
  - npm i -g eslint
install:
  - rm -rf node_modules && npm i
script:
  - cd $TRAVIS_BUILD_DIR/src
  - eslint -c package.json --max-warnings 1 src