language: node_js
os: linux
node_js:
  - 12
before_install:
  - cd $TRAVIS_BUILD_DIR/src
  - npm config set spin false
install:
  - rm -rf node_modules && npm i && npm i eslint -g && npm i babel-eslint --save-dev
script:
  - eslint index.js
  #- eslint -c package.json --max-warnings 1