language: node_js
os: linux
node_js:
  - 12
before_install:
  - cd $TRAVIS_BUILD_DIR/src
  - npm config set spin false
install:
  - sudo rm -rf node_modules
  - npm i
  - npm i eslint -g
  - npm i babel-eslint --save-dev
script:
  - eslint --no-eslintrc --env node --max-warnings 1 --parser babel-eslint --parser-options=ecmaVersion:6 main.js /