language: node_js
os: linux
node_js:
  - 12
before_install:
  - npm config set spin false
install:
  - rm -rf node_modules && npm i && npm i babel-eslint eslint --save-dev
script:
  - cd $TRAVIS_BUILD_DIR/src
  - eslint -c package.json --max-warnings 1 src