language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - 12
before_install:
  - cd $TRAVIS_BUILD_DIR/src
  - npm config set spin false
install:
  - npm discord.js && npm ci
script:
  - npm test