name: Node.js CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd src && npm i -g eslint && npm i babel-eslint --save-dev
      - run: cd src && eslint -c package.json --max-warnings 1
        env:
          CI: true