name: Node.js CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd src && npm ci
      - run: cd src && npm test
        env:
           BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
           WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}
           WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}